### ISSUE TITLE
How to set the font to Anonymice Powerline in cmder?

### ISSUE THREAD

**Issue by omniphx** [AmrEldib/cmder-powerline-prompt#1]
Hey might be a stupid question, but how do I set the font to Anonymice Powerline in cmder?

Will the .lau file load it as long as it's installed?

Thanks!

**Comment by AmrEldib** [comment]
Hi @omniphx 
You can set the font using the Settings dialog. On the left choose _Main_, then change the _Main console font_

**Comment by omniphx** [comment]
Oh thank you so much! For some reason, I've been using cmder for over a year and just realized I could click Main. Thought it was just a directory.. *doh!*
