### ISSUE TITLE
Custom prompt doesn't detect changes

### ISSUE THREAD

**Issue by loic-moriame** [AmrEldib/cmder-powerline-prompt#11]
Hello!

My cmder prompt doesn't worked as expected.
I follow your instructions, but my prompte always show me an unmodified git repo..

![cmder-powerline-prompt-error](https://cloud.githubusercontent.com/assets/536434/23029771/e57fb60a-f46b-11e6-887b-bb89d683e59b.png)

I guess the function get_git_status() doesn't return the right value.
I try an other function and it's works better:
```
---
 -- Get the status of working dir
 -- @return {bool}
---
function get_git_status()
    return os.execute("git diff --quiet --ignore-submodules HEAD")
end
``` 
![image](https://cloud.githubusercontent.com/assets/536434/23031641/fb55522c-f471-11e6-8e50-98f612c8a275.png)

I will make a pull request with my changes

**Comment by AmrEldib** [comment]
@moriame what version of Git to you have installed? You can find that by running `git --version`  
if you run the command `git status --no-lock-index`, do you get an error?  
The argument `--no-lock-index` was added in the latest git version 2.11

**Comment by loic-moriame** [comment]
Just make a fresh install of Cmder and I get this: 
```
λ git --version
git version 2.8.4.windows.1
``` 
and has expected: 
```
λ git status --no-lock-index
error: unknown option `no-lock-index' 
```

**Comment by AmrEldib** [comment]
I think updating git to 2.11 should resolve this.

**Comment by loic-moriame** [comment]
I just update "git-for-windows" inside ~/cmder/vendor to git 2.11.1: probleme resolve 👍
