### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by benavern** [AmrEldib/cmder-powerline-prompt#12]
Hi!

This is not an issue, I just wanted to say THANK YOU!
I used a big part of this code here : [https://github.com/benavern/cmder_custom](cmder customisations).
Is this a problem for you ? 
I modifyed it a bit :
* The status command was not working
* Styled node package informations
* ~ for home in pwd part & usable in commands

Hope you'll like it

**Comment by AmrEldib** [comment]
@benavern this is great! I really like adding additional (maybe we'll call them) carts.  
You can use the code with attribution, which I see you did in the README. 
I'm working on moving this prompt to PowerShell (which I'm switching to), and it'll be cool to add extra functionality. I might copy some of your ideas, if that's alright :)

**Comment by benavern** [comment]
Yes of course, you can !
Looking forward to see what you'll add...
I'll stay on CMD but maybe be able to help you customise this one the same way you'll do for powershell...

**Comment by AmrEldib** [comment]
@benavern here's the [powershell prompt](https://github.com/AmrEldib/cmder-powershell-powerline-prompt)
