### ISSUE TITLE
Can't get it to work with current version

### ISSUE THREAD

**Issue by mrchief** [AmrEldib/cmder-powerline-prompt#13]
I've followed up the readme to the letter, reinstalled from scratch, reset to factory settings and tried many things but I can't seem to get it working.

Any ideas? 

![image](https://cloud.githubusercontent.com/assets/781818/24365389/c3ac1b72-12e3-11e7-8040-e921e81495cd.png)

![image](https://cloud.githubusercontent.com/assets/781818/24365391/c84e4c54-12e3-11e7-8804-989b30e21e1b.png)

**Comment by mrchief** [comment]
Taking a cue from https://github.com/cmderdev/cmder/issues/990 and the fact that I wasn't getting the standard lambda prompty, I thought of uninstalling Clink that was installed system wide. And voila!

![image](https://cloud.githubusercontent.com/assets/781818/24367815/057042d8-12ec-11e7-8b4d-0bdbd68a90a5.png)

**Comment by johnyoonh** [comment]
@mrchief you made my day. Thank you so much!
