### ISSUE TITLE
Customizing not worked

### ISSUE THREAD

**Issue by Marlysson** [AmrEldib/cmder-powerline-prompt#14]
I putted the content of this repository in my clink.lua and restarted the cmder console , but nothing happened.

**Comment by AmrEldib** [comment]
Hi @Marlysson 
The file `powerline_prompt.lua` should be placed in the `%CMDER_ROOT%/config` folder.
Read more in the [Usage](https://github.com/AmrEldib/cmder-powerline-prompt) section
