### ISSUE TITLE
about (CJK) character directory 

### ISSUE THREAD

**Issue by zhang1900** [AmrEldib/cmder-powerline-prompt#16]
## description
*　add powerline,english directory is fine ,(CJK) character directory no good
*　no powerline,all is fine
![good_show](https://cloud.githubusercontent.com/assets/1811932/26280955/0e071540-3e19-11e7-808d-d46897a781a3.jpg)
![mistake-show](https://cloud.githubusercontent.com/assets/1811932/26280956/0ff6a1fe-3e19-11e7-90dc-79f2e612bcb0.jpg)

## environment
＊　cmder:Version v1.3.2
＊　OS:win7 64bit
＊　font file:DejaVu Sans Mono for Powerline
＊　options: add "set LANG=zh_CN.UTF-8", others is default value
![options](https://cloud.githubusercontent.com/assets/1811932/26280968/875c5478-3e19-11e7-9017-23e53af1c364.jpg)

**Comment by AmrEldib** [comment]
Hi @zhang1900 
Are you looking to add this as a feature, or are you having a problem with it? Please clarify. Thanks!

**Comment by ywyt738** [comment]
I have the same question.
In your lua file, you get the current dictory through ``clink.get_cwd()``.
According to https://github.com/mridgers/clink/issues/415, it returns ``windows-1252`` not ``utf-8``.

```lua
function lambda_prompt_filter()
    cwd = clink.get_cwd()
	if promptValue == promptValueFolder then
		cwd =  get_folder_name(cwd)
	end
    prompt = "\x1b[1;37;44m{cwd} {git}{hg}\n\x1b[1;30;40m{lamb} \x1b[0m"
    new_value = string.gsub(prompt, "{cwd}", cwd)
    clink.prompt.value = string.gsub(new_value, "{lamb}", "λ")
end
```
I guess that transfering the result of ``get_cwd()`` to utf-8, it will be ok, but I can't use lua. 😭
