### ISSUE TITLE
Diplay current directory, not the path.

### ISSUE THREAD

**Issue by DevotionGeo** [AmrEldib/cmder-powerline-prompt#17]
Thank You for the nice prompt! I didn't expect, that I'll be able to use that beautiful "Oh my zsh (zshell)" prompt inside windows. 
I never used Lua, so it will be very hard for me to find and edit the chunk of code responsible for adding full path to the prompt.

I'd like to have only current folder's name in the prompt without having the whole path.

Thank You again!

**Comment by AmrEldib** [comment]
[Line 5](https://github.com/AmrEldib/cmder-powerline-prompt/blob/master/powerline_prompt.lua#L5) in `powerline_prompt.lua` returns the current working directory. Splitting that string to get only the directory name should do the trick.
However, lua doesn't have a straightforward way to do this without an additional library. A function is needed that uses `strfind` and `strsub`. Here's a reference on [string manipulation](https://www.lua.org/manual/2.4/node22.html).

**Comment by AmrEldib** [comment]
Seems like this was an older version of lua. [Latest version](https://www.lua.org/manual/5.3/manual.html#6.4) makes it easier.

**Comment by AmrEldib** [comment]
@DevotionGeo I've updated the file to add this feature. Read [this section](https://github.com/AmrEldib/cmder-powerline-prompt#configuration) to use it.

**Comment by DevotionGeo** [comment]
Thank You so much!

I removed the newline and the λ character too, and now it looks super awesome!
![cmder](https://user-images.githubusercontent.com/7348138/27376264-066bbdd8-568b-11e7-9fbb-d98387951b81.JPG)
