### ISSUE TITLE
Customizing within git bash

### ISSUE THREAD

**Issue by OBats** [AmrEldib/cmder-powerline-prompt#19]
Hi.

Is there any way to use your customization with cmder_mini and git bash on it?
Just dropping `.lua` file in `%CMDER_ROOT%/config` doesn't help.

I prefer linux bash instead cmd. So will be very happy if there is such possibility. 

Thanks 👍

**Comment by AmrEldib** [comment]
I think if you prefer Linux bash, try using [ohmyzsh](http://ohmyz.sh/) especially if you use the new [Linux subsystem on Windows 10](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/). I use ohmyzsh on my Linux machine, and it's great.   
sorry for the late answer

**Comment by OBats** [comment]
Thanks for an answer!

I meant that I use cmder with [git for windows](https://git-scm.com/download/win) and it behaves just like the "git" command in LINUX and UNIX environments.

So I`m wondering is there any way to integrate your plugin with git for windows?

**Comment by AmrEldib** [comment]
@OBats I don't think this will work well. I had to [re-create this prompt to work in the PowerShell prompt](https://github.com/AmrEldib/cmder-powershell-powerline-prompt) in Cmder. I think it needs a similar effort to work in the Bash shell.

**Comment by digeomel** [comment]
I know this issue is closed, but I just wanted to ask the same question and I stumbled upon this. I'm using bash with cmder, too, and don't want to go back to the Windows command prompt just for this 😞
