### ISSUE TITLE
Missing latin characters

### ISSUE THREAD

**Issue by ararog** [AmrEldib/cmder-powerline-prompt#20]
Some latin characters like é ó ú are show as squares.

**Comment by AmrEldib** [comment]
I think the answer to that is related to ConEmu settings. See Alternative font and Unicode ranges in [Main Page](https://conemu.github.io/en/SettingsMain.html).  
Cmder uses ConEmu in the background.

**Comment by ararog** [comment]
No luck, I'm also using consolas as main font and Anonymice Powerline as alternative.

**Comment by AmrEldib** [comment]
@ararog do they show up like that when you type them or in the prompt as output?
I set up the same fonts and I could type without a problem (copied the letters you listed above and pasted them).
I'm using this Unicode range: `CJK: 2E80-9FC3;AC00-D7A3;F900-FAFF;FE30-FE4F;FF01-FF60;FFE0-FFE6;`

**Comment by mattdkerr** [comment]
@ararog can you use the test files in the cmder subdirectory to test your unicode, with powerline lua removed? because it shouldn't be related

**Comment by mattdkerr** [comment]
here are my settings, it seems to work well for me. I got my font from Nerd Fonts, the hacked Source Code Pro font and Inconsolata (Consolas hacked)

![image](https://user-images.githubusercontent.com/595328/40396061-eab28420-5ddf-11e8-83b4-7a89232b4a16.png)

works for me, recommend closing this as External / No Repro

**Comment by AmrEldib** [comment]
I'm closing this as _External / No Repro_
