### ISSUE TITLE
λ character disappeared

### ISSUE THREAD

**Issue by Starli0n** [AmrEldib/cmder-powerline-prompt#23]
Hi,

λ character disappeared after this step

* Download the .lua file, and place it in %CMDER_ROOT%/config folder.

![image](https://user-images.githubusercontent.com/3925813/33336995-e424e74e-d471-11e7-9eb7-654a6d5154dc.png)

But it seems to be there but not shown

![image](https://user-images.githubusercontent.com/3925813/33337134-4ce1f77c-d472-11e7-9445-b765120c0ecb.png)

Could you please help me to correct this bug ?

(I use Cmder Version v1.3.4)

**Comment by Starli0n** [comment]
I found the solution [there](https://github.com/cmderdev/cmder/issues/1529)

In line 24 from `powerline_prompt.lua`

Replace

`    prompt = "\x1b[37;44m{cwd} {git}{hg}\n\x1b[1;30;40m{lamb} \x1b[0m"`

by

`    prompt = "\x1b[37;44m{cwd} {git}{hg}\n\x1b[1;39;40m{lamb} \x1b[0m"`

**Comment by otherdave** [comment]
I just saw this too and was so glad to see an issue for it. @Starli0n do you want to open a PR for this so it gets back into the repo? I'm not sure how risky this is for anything else.

**Comment by AmrEldib** [comment]
@Starli0n thanks for reporting back the solution.  
The numbers are the ASCII colors. 
`[1;30;40m` is Bold on, Black foreground, and Black background
while
`[1;39;40m` is Bold on, Black background, but unknown foreground according to [this list](http://ascii-table.com/ansi-escape-sequences.php).

I think the customization is sensitive to the Cmder version. I haven't tested with the latest update. I'll try doing that.

**Comment by mattdkerr** [comment]
@AmrEldib I noticed that Cmder seems to pick up whatever the last color is set to on status line for the lambda on initial load of the prompt, for the rest of the session

**Comment by mattdkerr** [comment]
@Starli0n is this still an issue with latest version for you?

**Comment by mattdkerr** [comment]
No repro for me

**Comment by mattdkerr** [comment]
@AmrEldib I recommend closing this one as External
