### ISSUE TITLE
Feature - Change default branch colors

### ISSUE THREAD

**Issue by nickimola** [AmrEldib/cmder-powerline-prompt#26]
Hi,

This is not an issue, but rather a feature/assistance request.

Is it possible to change the colour of the branches?

I mean, white on green on my screen is really hard to read, so if master is "clean" i'd like to have it as black (foreground) on green arrow.

I try to change the colors in the lua config but without any luck.
Can you give me a quick hand on how to do this? and maybe change the background used (green/yellow) as well?

Thanks a lot

**Comment by AmrEldib** [comment]
@nickimola [this line](https://github.com/AmrEldib/cmder-powerline-prompt/blob/d1a3a40bf47b373cb83778fc846b3ce688868211/powerline_prompt.lua#L182) sets the color for a clean branch and the next line sets the color for a dirty branch.  
[This documentation page](http://ascii-table.com/ansi-escape-sequences.php) includes the different possible colors and how to set them.  
I hope this helps.

**Comment by nickimola** [comment]
Hi, yeah i closed it cause I found it. Thanks anyway :)
