### ISSUE TITLE
powerline_prompt.lua:194: attempt to call global 'get_git_branch' (a nil value)

### ISSUE THREAD

**Issue by easysun** [AmrEldib/cmder-powerline-prompt#28]
It can't show correctly when change directory to .git folder. The error as the following image.
![image](https://user-images.githubusercontent.com/5380578/36884718-8d7a80ac-1e1d-11e8-8530-c7696c67a721.png)

**Comment by jotka** [comment]
the same for me :-|

**Comment by sarisia** [comment]
Same here and found that this commit is the cause.
https://github.com/cmderdev/cmder/commit/29c5e839757f9bf9b649f63f534add408b723857

For temporary workaround, download clink.lua from this commit and replace
cmder/vendor/clink.lua with it.
https://github.com/cmderdev/cmder/commit/46d468aea09d59e260c57282b6c5de0d6e9f8b29

**Comment by mattdkerr** [comment]
The other solution to this would be to copy the get_git_branch function into the powerline_prompt.lua, making it not rely on the other present scripts.

**Comment by mattdkerr** [comment]
https://github.com/AmrEldib/cmder-powerline-prompt/pull/29

**Comment by lednhatkhanh** [comment]
Is this project not being maintained anymore?

**Comment by AmrEldib** [comment]
Thank you all for your participation, and Thank you @mattdkerr for fixing this.
My apologizes for the delay, I've been away lately.
