### ISSUE TITLE
Console full of "LF will be replaced by CRLF" warnings when in git directory

### ISSUE THREAD

**Issue by aplocher** [AmrEldib/cmder-powerline-prompt#3]
See screenshot below.  When I am in a git directory and type any command, I receive the warning (below) twice.

_warning: LF will be replaced by CRLF in .idea/.idea.Maranatha.DbApp/riderModule.iml.
The file will have its original line endings in your working directory._

![2016-12-17_01h14_35](https://cloud.githubusercontent.com/assets/1132447/21285746/76f87d5c-c3f6-11e6-810b-d5f1e0c1df04.png)

At least one seems to come from get_git_status ... appending `2>nul` to the command (as seen below) to fix the issue, but not sure if you want to suppress all warnings/errors coming from it (might be ok - I would think you wouldn't want them shown every time the prompt is shown...)

`git diff --quiet --ignore-submodules HEAD 2>nul`

**Comment by AmrEldib** [comment]
Thanks for reporting this, @aplocher I'll look into it

**Comment by AmrEldib** [comment]
I think Cmder is changing how it's checking the status of the Git repo to something that will suppress all warnings, and won't lock the repo a read-only operation. See [this line](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L228). This needs more investigation.

**Comment by aplocher** [comment]
Are you talking about using `git status` instead of `git diff`?  Their command is using the `2>nul` to prevent errors from showing.  That should fix this particular issue, whether its diff or status that's being called.

**Comment by AmrEldib** [comment]
Yes, it seems the latest version of Cmder has switched to using `git status` instead of `gis diff`, and they added `2>null` ([see here](https://github.com/cmderdev/cmder/blob/v1.3.2/vendor/clink.lua#L228)). I'll be updating to this.

**Comment by AmrEldib** [comment]
@aplocher checking git status has been updated. Let me know if there's still any issue. Thanks!
