### ISSUE TITLE
Dirty git repos not detected correctly

### ISSUE THREAD

**Issue by ivanjonas** [AmrEldib/cmder-powerline-prompt#31]
It seems that even dirty git repos will have the green "clean" flag. I narrowed down the problem to a mistyped git flag. PR incoming.

**Comment by ndraiman** [comment]
I'm still seeing this issue.

Removing the `--no-optional-locks` from the `io.popen()` call in `get_git_status()` function fixed it for me.

**Comment by ivanjonas** [comment]
That's really interesting. Was there anything special about your modified files that might have caused a difference? I found it unnecessary to remove that flag, so I'm curious about the difference between our experiences.

**Comment by ndraiman** [comment]
Maybe it's an issue with an old git version, its was a work computer.
