### ISSUE TITLE
addSegment?

### ISSUE THREAD

**Issue by GregoryShields** [AmrEldib/cmder-powerline-prompt#34]
I tried using your prompt and got the following message:
C:\Cmder\config\powerline_prompt.lua:66: attempt to call global 'addSegment' (a nil value)

It appears that it can't find the addSegment function, but I have no idea what I'm doing aside from that.

Incidentally, your instructions have a non-working example of using mklink. Your example shows hyphens and includes the word "cmder" in the .lua file name, but your actual file name doesn't have "cmder" and uses underscores. I had to modify it to this after cloning to my hard drive:
mklink /H powerline_prompt.lua C:\Code\Git\cmder-powerline-prompt\powerline_prompt.lua

**Comment by AmrEldib** [comment]
@gregshields sorry, the README should be updated to reflect the latest changes.
You should mklink for all file, especially: powerline_core.lua, powerline_prompt.lua, powerline_git.lua
_powerline_config.lua is for configurations
powerline_hg.lua is for Hg

**Comment by AmrEldib** [comment]
@gregshields I've edited the [README](https://github.com/AmrEldib/cmder-powerline-prompt/blob/master/README.md#usage) file to reflect latest changes

**Comment by GregoryShields** [comment]
Thanks for the update. It works!
Have you tried making it work with Bash/Git Bash?

I'm pretty ignorant about all of this and not sure what Hg is.

**Comment by AmrEldib** [comment]
@gregshields this prompt is inspired by one of OhMyZsh themes. For Linux shells, I recommend using [OhMyZsh](http://ohmyz.sh/), it's pretty powerful.

**Comment by GregoryShields** [comment]
Thank you. I appreciate it.
