### ISSUE TITLE
Git Conflict

### ISSUE THREAD

**Issue by sp3c1** [AmrEldib/cmder-powerline-prompt#35]
Would propose to set the git segment to red background and white text when following:
```
git diff --name-only --diff-filter=U
```
is not empty (this should give list of all files with conflict)

**Comment by mattdkerr** [comment]
Was this resolved in the last PR merge?

**Comment by AmrEldib** [comment]
@mattdkerr no, but should be possible to do

**Comment by mattdkerr** [comment]
@AmrEldib I see it in file powerline_git.lua:103 I just haven't tested it yet

**Comment by AmrEldib** [comment]
@mattdkerr it's working
![image](https://user-images.githubusercontent.com/769272/40438729-a29bbdb2-5e6d-11e8-863a-70f705670998.png)
