### ISSUE TITLE
config for optional characters doesn't work with SauceCodePro NF

### ISSUE THREAD

**Issue by mattdkerr** [AmrEldib/cmder-powerline-prompt#36]
![image](https://user-images.githubusercontent.com/595328/40384232-d7483664-5db7-11e8-9eb7-4a7f6c931fa0.png)
![untitled2](https://user-images.githubusercontent.com/595328/40384309-ff4d8f42-5db7-11e8-9a74-3b92eeea33e7.png)
font downloaded from https://nerdfonts.com/
used the search to find the unicode and character map to copy/paste them

**Comment by mattdkerr** [comment]
may just be a bug with the optional symbols? for now I have switched back to "full" instead of "smart" prompt type.

**Comment by AmrEldib** [comment]
it's a bug. In `powerline_npm.lua` line 52, this
```lua
if npmSymbol then
segment.text = " "..npmSymbol.." "..package_name.."@"..package_version.." "
```
should be 
```lua
if plc_npm_npmSymbol then
    segment.text = " "..plc_npm_npmSymbol.." "..package_name.."@"..package_version.." "
```

and, in `powerline_prompt.lua` line 65, this
```lua
if gitSymbol then
     cwd = gitSymbol.." "..cwd
```
should be
```lua
if plc_prompt_gitSymbol then
     cwd = plc_prompt_gitSymbol.." "..cwd
```
