### ISSUE TITLE
please help to display npm symbol

### ISSUE THREAD

**Issue by jeud** [AmrEldib/cmder-powerline-prompt#45]
Dear all

I have tried to follow the the [instruction](https://github.com/AmrEldib/cmder-powerline-prompt#font) on the *readme.md* but I couldn't figure out how to display the npm symbol on my prompt correctly

![](https://u.cubeupload.com/jeud/DTXLgR.png)
> I already installed [IcoMoon](https://icomoon.io/) fonts on my Windows, and copied & pasted the npm symbol as `npmSymbol = "` on the *power_core.lua* file

![](https://u.cubeupload.com/jeud/FybXUs.png)
> the above is my setting so far

![](https://u.cubeupload.com/jeud/xE8HOg.png)
> the symbol still appear incorrectly

Please guide
Thanks

**Comment by Darkensses** [comment]
@jeud you need to modify the line 53 in the powerline_npm.lua file
`segment.text = " "..npmSymbol.." "..package_name.."@"..package_version.." "`

change to:
`segment.text = " "..plc_npm_npmSymbol.." "..package_name.."@"..package_version.." "`

I hope this trick being useful 👍
