### ISSUE TITLE
The git prompt doesn't work?

### ISSUE THREAD

**Issue by ouweiya** [AmrEldib/cmder-powerline-prompt#46]
##### Why is the prompt for powerline_git.lua in %CMDER_ROOT%/config not to work?
Or what am I missing?
How does it pop up a prompt?

![snipaste_2018-11-17_22-59-14](https://user-images.githubusercontent.com/28357731/48662392-77d50300-eabc-11e8-94b8-a0055d52e701.png)

![snipaste_2018-11-17_23-02-38](https://user-images.githubusercontent.com/28357731/48662432-edd96a00-eabc-11e8-9b27-8415d0c2fa34.png)

**Comment by mattdkerr** [comment]
what happens if you copy all of the lua files into your config directory?
