### ISSUE TITLE
Error when loading clink lua scripts

### ISSUE THREAD

**Issue by eblis** [AmrEldib/cmder-powerline-prompt#61]
I'm trying to run your lua scripts with ConEmu and clink (installed globally) and I've copied the scripts to where I think clink expects them: c:/users/<user>/appdata/local/clink/*.lua but when I start ConEmu i get the following error:

`C:\Users\<user>\AppData\Local.\clink\powerline_prompt.lua:57: bad argument #2 to 'find' (string expected, got no value)`

the line in question is:
`        if plc_prompt_useHomeSymbol and string.find(cwd, clink.get_env("HOME")) and git_dir ==nil then 
`

**Comment by eblis** [comment]
Setting `plc_prompt_useHomeSymbol = false` gets rid of the issue - seems to be something related to showing pretty icons instead of my home folder

**Comment by patstew** [comment]
You need to change
`clink.get_env("HOME")`
to
`clink.get_env("HOMEDRIVE") .. clink.get_env("HOMEPATH")`
on that line and the line below.

**Comment by eblis** [comment]
Thanks, I'll give it a try and report back.

I've also noticed a weird issue since installing this, but I didn't have time to investigate it yet.
Basically I can no longer paste code with ctrl + shift + insert in conemu, only right clicking works.
I've also added some `aliases` for `ll` and `cd /d` which have also stopped working. It is as if the conemu scripts are no longer executed

**Comment by eblis** [comment]
That seems to have solved both issues.
I can now paste using shift+insert, my aliases work and I don't get an error when home symbol is enabled.

Thanks
