### ISSUE TITLE
Accented characters not working

### ISSUE THREAD

**Issue by Neluji** [AmrEldib/cmder-powerline-prompt#65]
The accented characters (like the É or the À that I use as I am French) aren't recognized when inside the path, like here :
![image](https://user-images.githubusercontent.com/38362829/84157139-a6ce1380-aa6a-11ea-94a5-5a46c9f842da.png)
Behaves in the same way for lowercase or uppercase letters.

(PS: Yes I know it's not a good practice to name folders with accented characters, but I preferred reporting it anyway...)

**Comment by chrisant996** [comment]
I think that's a Clink limitation, not a cmder-powerline-prompt issue.

And it's working in the [chrisant996/clink](https://github.com/chrisant996/clink) fork of Clink.
