### ISSUE TITLE
Promt does not change

### ISSUE THREAD

**Issue by bitbonk** [AmrEldib/cmder-powerline-prompt#7]
I installed Cmder using `choco install cmder` today. It was installed into **c:\tools\cmder**
Then I downloaded [the fonts](https://github.com/powerline/fonts) and installed them all using **install.ps1** from that repo.
Then I downloaded **powerline_prompt.lua** from this repo and placed it in **powerline_prompt.lua**.
Then I restarted Cmder.

Nothing happens, the promit still looks the same:

![image](https://cloud.githubusercontent.com/assets/418030/22087721/d1655c94-dddf-11e6-90b6-9a2cec001339.png)

Don't I need to do something that the **powerline_prompt.lua** is executed? When is Cmder executing this script?

**Comment by AmrEldib** [comment]
Hi @bitbonk 
make sure the instance of Cmder you're running is at the same location as the instance you install the `.lua` file to.
In the command line, type `echo %CMDER_ROOT%`.
Make sure the current instance is at the same location. You can use `which cmder`, or use the Windows Task Manager to figure out the location of the Cmder process.
Make sure to place the file at `%CMDER_ROOT%\config`

**Comment by bitbonk** [comment]
OK, I guess this prompt only works if I start `cmder.exe` directly. When I start `cmd.exe` (which was preplaced with cmder) or when I start  `{Git bash}` this kind of prompt is not there.

![image](https://cloud.githubusercontent.com/assets/418030/22088563/48733478-dde5-11e6-9dc3-cd987a1348b8.png)
![image](https://cloud.githubusercontent.com/assets/418030/22088598/9174af76-dde5-11e6-9c24-c9849f7fa178.png)

However there still seems something wrong with my prompt because there are some error messages.
![image](https://cloud.githubusercontent.com/assets/418030/22088612/a265e5f2-dde5-11e6-9b70-01fb2766d92e.png)

**Comment by AmrEldib** [comment]
It's normal for the prompt to only work with `Cmder` and not the other shells. That's expected. 

As for the Git error, this seems to happen to new repos (see this [SO answer](http://stackoverflow.com/questions/12267912/git-fatal-ambiguous-argument-head-unknown-revision-or-path-not-in-the-workin#12887486)). Maybe there's something we can do to avoid using HEAD. PR #6 changes the git command to avoid HEAD. I think it should resolve this issue.   

I'll look into the issue with the special character.

**Comment by AmrEldib** [comment]
@bitbonk I've added a [Font](https://github.com/AmrEldib/cmder-powerline-prompt#font) section to README to clarify how the symbol can show correctly while using a different font.
The git error should be resolved now as well. I'll close this, but please let me know if you're still have problems. Thanks!

**Comment by bitbonk** [comment]
Wow, what an impressive reponse time! Thanks, everything works fine now!

**Comment by AmrEldib** [comment]
@bitbonk lol, you just got lucky this time, I was scheduled to work on this yesterday :)
