### ISSUE TITLE
Slow feedback

### ISSUE THREAD

**Issue by tvercruysse** [AmrEldib/cmder-powerline-prompt#8]
Command has no lag, but returning the prompt in a git repo results in lag. due to old way of checking for diff. (cmder updated this. if i was any better in lua i would fix it myself, but i cant.)

**Comment by AmrEldib** [comment]
@tvercruysse  I've recently changed how git status is checked following Cmder example, can you explain how Cmder updated this? Thanks!

**Comment by tvercruysse** [comment]
Like i said, im a total noob in Lua development. but ill do a PR and replace it with my current file.
